server:
  servlet:
    session:
      timeout: 60m
  http:
    port: 8080
  port: 8400

  ssl:
    enabled: true
    key-alias: freelog-keystore
    key-store: freelog-keystore.pkcs12
    key-store-password: 'Ww44226003!@'
    key-password: 'Ww44226003!@'
    trust-store: freelog-trust.pkcs12
    trust-store-password: 'Ww44226003!@'

  tomcat:
    threads:
      max: 500
      min-spare: 30
    max-connections: 10000
    accept-count: 200
    max-http-form-post-size: 20MB

spring:
  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

    remote:
      restart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    master:
      hikari:
        username: root
        password: wnsah12
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3310/jmblog_mariadb
        pool-name: jmblog_mariadb_master

    slave:
      hikari:
        username: root
        password: wnsah12
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3311/jmblog_mariadb
        pool-name: jmblog_mariadb_slave

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      ddl-auto: update
      use-new-id-generator-mappings: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: apdh1709@gmail.com
    password: peroixuyuocvnsze
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 100000
          connectiontimeout: 60000
          writetimeout: 60000


  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
        max-wait: 500
    port: 6379
    host: localhost
    connect-timeout: 5000
    timeout: 1500

    session:
      timeout: 600  # 10분
      store-type: redis
      redis:
        flush-mode: on_save


springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: swagger-ui-custom.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.service.core


logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ./logs/JmBlog.log
    max-history: 30

  level:
    root: INFO
    com.service: INFO

    org.hibernate:
#      SQL: debug
#      type.descriptor.sql: trace

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

scheduler:
  find-user-info: "* * 0 * * *"

util-config:
  aws_ec2_sftp:
    ip: 192.584.34.343
    port: 22
    id: id
    password: password
    directory: directory
    timeout: 100

  aws_s3-bucket:
    access_key_id: AKIA3Y4KG56CSZH7JPWR
    secret_access_key_id: yqoNogJhlu+ifSJqJJkUU4W6oTtw6R9gj6ZrCgDt
    bucket_name: freelog-s3-bucket

