server:
  servlet:
    session:
      timeout: 60m

  compression:
    enabled: true

  port: ${SERVER_PORT}

  tomcat:
    threads:
      max: 500
      min-spare: 50
    max-connections: 10000
    accept-count: 1000
    max-http-form-post-size: 50MB

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    include: env

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

    remote:
      restart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    master:
      hikari:
        username: ${DB_MASTER_USERNAME}
        password: ${DB_MASTER_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://${DB_MASTER_IP}:${DB_MASTER_PORT}/${DB_MASTER_SCHEMA}?useUnicode=yes&characterEncoding=UTF-8
        pool-name: ${DB_MASTER_POOL}

    slave:
      hikari:
        username: ${DB_SLAVE_USERNAME}
        password: ${DB_SLAVE_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://${DB_SLAVE_IP}:${DB_SLAVE_PORT}/${DB_SLAVE_SCHEMA}?useUnicode=yes&characterEncoding=UTF-8
        pool-name: ${DB_SLAVE_POOL}

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      ddl-auto: ${DDL_AUTO}
      use-new-id-generator-mappings: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: ${BATCH_SIZE}
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 100000
          connectiontimeout: 60000
          writetimeout: 60000


  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        max-wait: 1000
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
    connect-timeout: 100000
    timeout: 180000

    session:
      timeout: 3600  # 1시간
      store-type: redis
      redis:
        flush-mode: on_save
    password: ${REDIS_PASSWORD}


springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: swagger-ui-custom.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.service.core


logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ./logs/freeblog.log
    max-history: 30

  level:
    root: INFO
    com.service: INFO

    org.hibernate:
#      SQL: debug
#      type.descriptor.sql: trace

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

### util config ###
util-config:
  # SFTP VM CONFIG
  # 저장 타입: images | videos
  aws_ec2_sftp:
    protocol: ${AWS_EC2_SFTP_PROTOCOL}
    ip: ${AWS_EC2_SFTP_IP}
    port: ${AWS_EC2_SFTP_PORT}
    id: ${AWS_EC2_SFTP_ID}
    password: ${AWS_EC2_SFTP_PASSWORD}
    directory: ${AWS_EC2_SFTP_DIRECTORY}
    timeout: ${AWS_EC2_SFTP_TIMEOUT}

  # AWS CONFIG
  aws_s3-bucket:
    access_key_id: ${AWS_S3_BUCKET_ACCESS_KEY_ID}
    secret_access_key_id: ${AWS_S3_BUCKET_SECRET_ACCESS_KEY_ID}
    bucket_name: ${AWS_S3_BUCKET_NAME}

  # SQL CONFIG
  sql_config:
    # FULL-TEXT | LIKE
    sql_search_pattern: LIKE

  # APP CONFIG
  app_config:
    # 인증 이메일 주소 프로토콜
    auth_email_addr_protocol: ${AUTH_EMAIL_ADDR_PROTOCOL}
    auth_email_addr_url: ${AUTH_EMAIL_ADDR_URL}
    auth_email_addr_port: ${AUTH_EMAIL_ADDR_PORT}
    # 최신,인기 게시글 조회 개수
    recent_popular_post_count: 5
    # 최신 댓글 조회 개수
    recent_comment_count: 5
    # 사용자 좋아요 누른 게시글 저장 만료 기한 (30일)
    user_like_post_expire_days: 2592000
    # 사용자 좋아요 누른 게시글 최대 저장 개수 (100개)
    user_like_post_max_count: 100
    # 게시글 최대 사이즈
    max_post_content_size: 100000000